[package]
name = "plot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.3.5"

[build-dependencies]
bindgen = "0.68.1"
copy_to_output = "2.1.0"
